snowGraph:
    projectPackageName: SmartCity
    boltUrl: bolt://162.105.88.28:7688/
    dataDir: E:/SnowGraphData/dc/snow
    githubAccessToken: b0603b617a6cb24a447a308ad71f95a4e5c87783
server:
    port: 8081